server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index mobile-preview.html;

  location = / {
    try_files /mobile-preview.html =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
